Initial support for Netberg 610, 710, 750 Aurora Switches
stratum/stratum pull request #318
Opened 2020-08-26 13:40 UTC by andrewsapronov

Please merge initial support for barefoot based NetBerg Switches.

2020-08-26 20:46 UTC, pudelkoM commented
Looks good to me.
Two things to fix:

- Sign a CLA as instructed
- Can you confirm that the directory names (`x86-64-netberg-aurora-610-r0`) are identical to the onl platform names under `/etc/onl/platform`? There is some program logic that depends on this fact.

2020-08-27 19:09 UTC, pudelkoM commented
Since you did not allow edits by maintainers, you will also have to add these lines to the BUILD file yourself:

```Bazel
platform_config_test("x86-64-netberg-aurora-610-r0")
platform_config_test("x86-64-netberg-aurora-710-r0")
platform_config_test("x86-64-netberg-aurora-750-r0")
```

2020-08-28 15:35 UTC, andrewsapronov commented
Hi Maximilian, 

CLA has been signed.

I've added our platforms to the BUILD and we confirm that `/etc/onl/platform` is identical to directory names.

Could you please also advise what kind of permission you mentioned?

--
BR, 
Andrew

2020-08-28 17:07 UTC, pudelkoM commented
> Could you please also advise what kind of permission you mentioned?

GH has the option to allow edits by maintainers (us): https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork
It's not needed anymore since you did the changes yourself.

Thanks for checking the names. I think we can merge this now.

2020-08-28 17:07 UTC, pudelkoM submitted a review, later dismissed

2020-09-01 16:55 UTC, Yi-Tseng requested changes

2020-09-01 16:55 UTC, Yi-Tseng commented on stratum/hal/config/x86-64-netberg-aurora-610-r0/port_map.json
> +  "_comment": "Configuration file for bspless support on x86-64-netberg-aurora-710-r0",
`support on x86-64-netberg-aurora-610-r0` ?

2020-09-01 16:55 UTC, Yi-Tseng commented on stratum/hal/config/x86-64-netberg-aurora-710-r0/port_map.json
> +  "_comment": "Configuration file for bspless support on x86-64-netberg-aurora-750-r0",
`x86-64-netberg-aurora-710-r0` ?

2020-09-01 16:55 UTC, Yi-Tseng commented on stratum/hal/config/x86-64-netberg-aurora-710-r0/port_map.json
> +  "_comment": "Configuration file for bspless support on x86-64-netberg-aurora-750-r0",
Maybe this is a wrong port map file for Aurora 710 since it has more than 32 ports(connectors).
Can you check again?

2020-09-01 16:55 UTC, Yi-Tseng commented on stratum/hal/config/x86-64-netberg-aurora-750-r0/port_map.json
> +  "_comment": "Configuration file for bspless support on x86-64-netberg-aurora-710-r0",
I think this should be the correct file for Aurora 710.

2020-09-04 17:18 UTC, pudelkoM commented
Looks good.
I'll leave it to Yi to merge this

2020-09-04 18:46 UTC, Yi-Tseng approved these changes

2020-09-04 19:35 UTC, pudelkoM commented
@andrewsapronov please rebase this PR on latest master, otherwise we can't merge. Or enable maintainer edits as explained above.

2020-09-07 15:46 UTC, andrewsapronov commented
> @andrewsapronov please rebase this PR on latest master, otherwise we can't merge. Or enable maintainer edits as explained above.

@pudelkoM  I've made rebase. Please check. 

BTW, I spent some time but I couldn't find 'tick' for enabling edits :(

2020-09-07 18:03 UTC, pudelkoM commented
Thanks!

Here is the checkbox:
![Capture](https://user-images.githubusercontent.com/7455710/92410631-9aa13300-f0f9-11ea-91f6-ec02e94246e0.PNG)

2020-09-07 18:03 UTC, pudelkoM approved these changes

2020-09-07 18:04 UTC, merged